### ISSUE TITLE
The authenticate() function may fail with no console error message for certain error types

### ISSUE THREAD

**Issue by jmychasiw** [saadichouaib/codeceptjs-xray-cloud-helper#1]
## Context
Found that for specific type of firewall error in my organization, the `authenticate()` would fail without showing the cause of the error.
The suppressed error for me was ` Error: unable to get local issuer certificate`.
I was able to expose the root cause by modifying the existing `console.error()` line. See below.

## Expected Behavior
The error message should be output the same as other related error messages so such as:
```
 Authentication error while importing Xray results, reason :
 { error: 'Authentication failed. Invalid client credentials!' }
```

## Actual Behavior
The console displays authentication progress but then exits and shows nothing and the Xray import did not take place
```
...
 ✔ Invalid Email Address | {"emailAddress":".boldy@boldcommece.com"} in 0ms

  OK  | 14 passed   // 10s
```

## Troubleshooting
I was able to modify [this line](https://github.com/saadichouaib/codeceptjs-xray-cloud-helper/blob/develop/api/xray_api.js#L38) to just print the raw error.  similar to something like:
```console.error(`Authentication error while importing Xray results, reason :\n ${err}`);```

And was able to get the following output:
```
Authentication error while importing Xray results, reason :
 Error: unable to get local issuer certificate
```

**Comment by saadichouaib** [comment]
@jmychasiw 

Could you please try @aminekun90's solution with your specific case : 

[https://github.com/saadichouaib/codeceptjs-xray-cloud-helper/pull/3
08fce81cc67a04dfb7d81fc59765e43e26bb4ac7](https://github.com/saadichouaib/codeceptjs-xray-cloud-helper/pull/3/commits/08fce81cc67a04dfb7d81fc59765e43e26bb4ac7)

**Comment by jmychasiw** [comment]
See : https://github.com/saadichouaib/codeceptjs-xray-cloud-helper/pull/3#issuecomment-1529707665
