### ISSUE TITLE
Could not load plugin xrayImport from module 'codeceptjs-xray-cloud-helper' on Gitlab CI

### ISSUE THREAD

**Issue by jmychasiw** [saadichouaib/codeceptjs-xray-cloud-helper#4]
## Context
Currently testing Xray Plugin on my local workstation with success but getting this error when I try to run my project on Gitlab CI.
Still working with the problem, but my `.gitlab-ci.yml` very simple (one we use with our other project).  
I can submit more concise code example but I am wondering any else has been able to run this on Gitlab CI with success ?

```
Could not load plugin xrayImport from module 'codeceptjs-xray-cloud-helper':
Cannot find module 'codeceptjs-xray-cloud-helper'
Require stack:
- /codecept/lib/container.js
- /codecept/lib/codecept.js
- /codecept/bin/codecept.js
Error: Cannot find module 'codeceptjs-xray-cloud-helper'
Require stack:
- /codecept/lib/container.js
- /codecept/lib/codecept.js
- /codecept/bin/codecept.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/codecept/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:833:27)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at createPlugins (/codecept/lib/container.js:291:29)
    at Function.create (/codecept/lib/container.js:47:25)
    at Codecept.init (/codecept/lib/codecept.js:56:15)
    at module.exports (/codecept/lib/command/run.js:28:14)
    at Command.<anonymous> (/codecept/bin/codecept.js:9:11)
Error: 
    at createPlugins (/codecept/lib/container.js:293:13)
    at Function.create (/codecept/lib/container.js:47:25)
    at Codecept.init (/codecept/lib/codecept.js:56:15)
    at module.exports (/codecept/lib/command/run.js:28:14)
    at Command.<anonymous> (/codecept/bin/codecept.js:9:11)
    at Command.listener (/codecept/node_modules/commander/index.js:315:8)
    at Command.emit (node:events:513:28)
    at Command.parseArgs (/codecept/node_modules/commander/index.js:651:12)
    at Command.parse (/codecept/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/codecept/bin/codecept.js:240:9)
```

**Comment by saadichouaib** [comment]
Hello @jmychasiw.

Yes actually I'm using it in gitlabci. 
What does your package.json look like?

**Comment by jmychasiw** [comment]
```
{
    "name": "codeceptjs-tests",
    "version": "0.1.0",
    "private": true,
    "scripts": {
        "codeceptjs": "codeceptjs run --steps",
        "codeceptjs:headless": "HEADLESS=true codeceptjs run --steps"
    },
    "devDependencies": {
        "@codeceptjs/configure": "^0.10.0",
        "@types/node": "^18.14.6",
        "codeceptjs": "^3.4.1",
        "codeceptjs-xray-cloud-helper": "^2.0.0",
        "dotenv": "^16.0.1",
        "js-yaml": "^4.1.0",
        "playwright": "^1.32.2",
        "ts-node": "^10.9.1",
        "typescript": "^4.9.5"
    }
}

```

**Comment by saadichouaib** [comment]
That's weird if we assume that xrayImport config is ok in your codecept.conf.js file.

I will try to push a hands on project using the lib and gitlabci config tomorrow if it would be helpful 👍.

**Comment by jmychasiw** [comment]
Yes that would be helpful.  For the Record: `codecept.conf.ts`
```
import { setHeadlessWhen, setCommonPlugins } from '@codeceptjs/configure';
import { conf } from "./config/config";

// turn on headless mode when running with HEADLESS=true environment variable
// export HEADLESS=true && npx codeceptjs run
setHeadlessWhen(process.env.HEADLESS);

// enable all common plugins https://github.com/codeceptjs/configure#setcommonplugins
setCommonPlugins();

export const config: CodeceptJS.MainConfig = {
  tests: './*_test.ts',
  output: './output',
  helpers: {
    Playwright: {
      url: 'http://localhost',
      show: false,
      browser: 'chromium'
    }
  },
  include: {
    I: './steps_file'
  },
  plugins: {
    xrayImport: {
      require: "codeceptjs-xray-cloud-helper",
      enabled: conf.xray_plugin_config.enabled,
      debug: conf.xray_plugin_config.debug,
      projectKey: conf.xray_plugin_config.jira_project_key,
      importToExistingTestExecution: false,
      testExecutionPlanKey: conf.xray_plugin_config.test_plan_key,
      testExecutionEnvironments: conf.xray_plugin_config.test_execution_environments,
      testExecutionSummary: conf.xray_plugin_config.test_execution_summary,
      testExecutionDescription: conf.xray_plugin_config.test_execution_description,
      testExecutionSendEvidenceOnFail: true,
      createNewJiraTest: false,
      timeout: 120000,
      xrayClientId: conf.xray_auth.xray_client_id,
      xraySecret: conf.xray_auth.xray_client_secret
    },
    screenshotOnFail: {
      enabled: true,
      uniqueScreenshotNames: true
    },
    commentStep: {
      enabled: true,
      registerGlobal: 'xray_'
    }
  },
  name: 'xray-plugin-demo'
}
```

**Comment by saadichouaib** [comment]
sorry for the delay, I just pushed https://github.com/saadichouaib/hands-on-codeceptjs-xray-cloud-helper.

Don't hesitate if you have any question

**Comment by jmychasiw** [comment]
Thanks.
In your configuration I noticed the different docker image in your CI config.

I am not an expert with Docker at this time but I was able to narrow down the problem to the fact that I am using the `codeceptjs/codeceptjs` image from [Codecept docker](https://codecept.io/docker.html) .

I attached a very minimal stripped down codeceptJS project that runs in Gitlab.
[See attached xray-plugin-gitlab-config-main.zip](https://github.com/saadichouaib/codeceptjs-xray-cloud-helper/files/11502352/xray-plugin-gitlab-config-main.zip)

The problem can be recreated by changing the base docker image from `image: node:lts-bullseye` to `image: codeceptjs/codeceptjs` 

Using the `image: codeceptjs/codeceptjs`  image, the error occurs:

```
Error: Cannot find module 'codeceptjs-xray-cloud-helper'
Require stack:
- /codecept/lib/container.js
- /codecept/lib/codecept.js
- /codecept/bin/codecept.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/codecept/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:833:27)
```

Our company generally uses the  [Codecept docker](https://codecept.io/docker.html)  image with success. Is it possible that the image you use satisfies the dependencies that are missing otherwise?

Hope this helps

**Comment by saadichouaib** [comment]
I just tested the same project using image `codeceptjs/codeceptjs` and the run was successful 🤔.

I was able to reproduce the same error you had by requiring a wrong module in xrayImport configuration : `require: "making-error-codeceptjs-xray-cloud-helper",`

I don't know how but it seems like `codeceptjs-xray-cloud-helper` is not installed on your ci.

**Comment by jmychasiw** [comment]
Thanks for the reply and testing that project.

I will dig into this problem more but I have some comments to note:
According to the error above, the root cause is that it cannot find the specific file `source-map-support.js`:
`/codecept/node_modules/@cspotcode/source-map-support/source-map-support.js:811:3`

As part of the CICD job, the install info is printed out as well as the **contents of the `node_modules` folder**.
The output shows that all of the libraries are  retrieved and existing in place when I print out the `node_modules` folder

See full [xray-plugin-error.log](https://github.com/saadichouaib/codeceptjs-xray-cloud-helper/files/11510922/xray-plugin-error.log)

**Comment by jmychasiw** [comment]
Still experimenting with this issue and trying to narrow down why [Gitlab cannot find the source-map-support dependency](https://github.com/saadichouaib/codeceptjs-xray-cloud-helper/issues/4#issuecomment-1553534937) when using an image. 

Would it possible to get the docker compose file you are using to build the image used in your example.

**Comment by jmychasiw** [comment]
Though I still have not been able to track this problem down, it is not a problem for our organization at this time as we are moving to Github  Enterprise.
