### ISSUE TITLE
Test Results excluded from Xray export when using Scenario level retry()

### ISSUE THREAD

**Issue by jmychasiw** [saadichouaib/codeceptjs-xray-cloud-helper#7]
## Context
I am finding that for some builds a test does not get added to the export. When this problem occurs I notice console messages printed around the test such as:
> TypeError: Cannot read properties of undefined ....

## Actual Behavior
When the problem occurs the follow console messages appear right near the test that is being executed.
>TypeError: Cannot read properties of undefined (reading 'toString')
>TypeError: Cannot read properties of undefined (reading 'toUpperCase')
>TypeError: Cannot read properties of undefined (reading 'every')

In this example the single test passes, and the **TypeError**s are displayed in the console and then the "0 test validation error" is thrown and fails the build. _(BTW I was planning on submitting a question around the behaviour of this validation error as it fails the build.  Not sure if the that is preferred. However this other issue is more pressing)_

```
CodeceptJS v3.4.1 #StandWithUkraine
Using test root "/builds/e2e-tests"

Three page checkout --
TypeError: Cannot read properties of undefined (reading 'toString')
TypeError: Cannot read properties of undefined (reading 'toUpperCase')
  ✔ Checkout with matching Canadian shipping and billing addresses (GUEST USER) @TEST_PXP-858 in 73196ms
TypeError: Cannot read properties of undefined (reading 'every')

  OK  | 1 passed   // 5m
Send results to JIRA : 
{
  "info": {
    "project": "PXP",
    "summary": "E2E Test Execution in Branch link-taxes-tests",
    "description": "E2E Test execution automatically created from Gitlab ",
    "version": "",
    "revision": "",
    "startDate": "2023-08-10T18:10:07+00:00",
    "finishDate": "2023-08-10T18:15:13+00:00",
    "testPlanKey": "PXP-760",
    "testEnvironments": []
  },
  "tests": []
}
Error in xray execute import body, please refer to the developer. 
Reason : 
 [
  ValidationError {
    path: [ 'tests' ],
    property: 'instance.tests',
    message: 'does not meet minimum length of 1',
    schema: { type: 'array', items: [Object], minItems: 1 },
    instance: [],
    name: 'minItems',
    argument: 1,
    stack: 'instance.tests does not meet minimum length of 1'
  }
]
```

## Steps to Reproduce the Problem
 This problem seems to be intermittent and difficult to reproduce.  

* The build runs on Gitlab.
* Node version: v18.17.0
* CodeceptJS 3.4.1 with Typescript

Seems that the three missing properties exist in `index.js`. 
Not sure why the `test` object would not be available after the event is fired. 
```
event.dispatcher.on(event.test.after, function (test) {
        recorder.add('Get test results', function () {
            //Get test status
            const status = test.state.toUpperCase();

            let test_contains_examples = false;
            let test_contains_iterations = false;

            //Get tag from test, this tag will be used as a testKey in the api to link the test execution with a JIRA test (if createNewJiraTest is false)
            test.tags.every(tag => {
                if (tag.toString().includes("@TEST_")) {
                    test_key = tag.split("@TEST_")[1];
                    return false;
                } else {
                    test_key = "no_xray_tag";
                }
                return true;
            });

        ....
```

**Comment by saadichouaib** [comment]
Hi @jmychasiw, 

it seems like `test` object inside `event.dispatcher.on(event.test.after, function (test)` in `index.js` is empty. 
could you please try to print `test` before this line `const status = test.state.toUpperCase();`

Concerning below error, its a schema validation that runs before the xray api call.
In your case, you get the error because there is no test result and in that case Xray api call would fail anyway that's why I prefer to fail even before the api call.

```
Reason : 
 [
  ValidationError {
    path: [ 'tests' ],
    property: 'instance.tests',
    message: 'does not meet minimum length of 1',
    schema: { type: 'array', items: [Object], minItems: 1 },
    instance: [],
    name: 'minItems',
    argument: 1,
    stack: 'instance.tests does not meet minimum length of 1'
  }
]
```

**Comment by jmychasiw** [comment]
Update: this problem can be reproduced when using  [Retry Scenario](https://codecept.io/basics/#retry-scenario) 

Upon running in debugger I observed that that the `test.status` property is `undefined` when the scenario is being retried.
In `index.js`,
``` 
//Get test status
const status = test.state.toUpperCase();
```
Will create the error: `TypeError: Cannot read properties of undefined (reading 'toUpperCase')`

The attached project demonstrates this problem.
[xray-plugin-bugtest.zip](https://github.com/saadichouaib/codeceptjs-xray-cloud-helper/files/12652069/xray-plugin-bugtest.zip)

**Comment by saadichouaib** [comment]
Thanks @jmychasiw for your analysis. It explains a lot finally 👏 

Actually, retry feature is not taken into account by the lib, it's something we should work on it 👍
