### ISSUE TITLE
 Environments don't exist exception

### ISSUE THREAD

**Issue by venkata-qa** [saadichouaib/codeceptjs-xray-cloud-helper#9]
## Context
I have cloned this [example](https://github.com/saadichouaib/hands-on-codeceptjs-xray-cloud-helper) repository, and added all the necessary information in the config data.
And also I have removed the testExecutionEnvironments property assuming that it is not mandatory.

## Expected Behavior
Test case should be imported to Jira

## Actual Behavior
Error while importing Xray results, reason :
 {
  error: "Error importing results: the following environments dont exist or are not in the context of test execution project: 'QA'!"
}

## Steps to Reproduce the Problem

- 1 Clone this repo https://github.com/saadichouaib/hands-on-codeceptjs-xray-cloud-helper
- 2 Updated the config, and remove the testExecutionEnvironments property
- 3 Run the tests

**Comment by saadichouaib** [comment]
Hello @venkata-qe, thank you for submitting this issue. In fact, ["QA"] is a default value.

It will be fixed soon, meanwhile you can try using `testExecutionEnvironments: [""]`

**Comment by venkata-qa** [comment]
Thanks for your reply @saadichouaib 

I have tried by setting this value testExecutionEnvironments: [""], but still getting the similar error 
Error while importing Xray results, reason :
 {
  error: "Error importing results: the following environments dont exist or are not in the context of test execution project: ''!"
}

Do you have any other workaround?

**Comment by saadichouaib** [comment]
Or you can just create an environment in Xray and use it ?
@venkata-qe

**Comment by venkata-qa** [comment]
Thanks @saadichouaib 
It is working after creating the environment
